name: modbus
version: 0.1.1
author: "Pavel Sokolov <pavel@sokolov.me>"
homepage: https://github.com/Hacker-CB/modbus-dart
description: MODBUS dart library.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1

dev_dependencies:
  test: ^1.17.10
